--insert into employee (id, name, email, phno) values(1,'praveen','ahuui@gmail.com',31253);
--insert into employee (id, name, email, phno) values(2,'fgga','awwagr@gmail.com',3453);
--insert into employee (id, name, email, phno) values(3,'psgs','arwgrqsssfd@gmail.com',3311253);
--insert into employee (id, name, email, phno) values(4,'psagsaen','asfsadwui@gmail.com',31251343);
--insert into employee (id, name, email, phno) values(5,'sseen','qui@gmail.com',5541253);